import './functions/publish';
import './functions/getCatalogue';
import './functions/getProgress';
import './functions/postProgress';
import './functions/getEnrolment';
import './functions/listMedia';
import './functions/uploadMedia';
import './functions/getPage';
import './functions/savePage';
